<a href="https://colab.research.google.com/github/aluqbnle/ml-sandbox/blob/master/lecture_chap02_exercise_master.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 松尾研のハンズオンをやっていく

## https://karaage.hatenadiary.jp/entry/2018/01/31/073000

## numpy

In [0]:
import numpy as np

In [2]:
W = np.array([[1,2,3],[4,5,6]])
x = np.array([7,8,9])

print(W)
print(x)

[[1 2 3]
 [4 5 6]]
[7 8 9]


In [3]:
print(W.shape)
print(x.shape)

(2, 3)
(3,)


In [6]:
x_row = np.array([[7,8,9]])
x_col = np.array([[7],[8],[9]])

print(x_row.shape)
print(x_col.shape)

(1, 3)
(3, 1)


In [11]:
print(np.zeros(10))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(np.ones(10))
print(np.ones((3,3)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
print(np.arange(10))
print(np.arange(3,7))
print(np.arange(1,10,0.1))

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
