<a href="https://colab.research.google.com/github/aluqbnle/ml-sandbox/blob/master/lecture_chap02_exercise_master.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 松尾研のハンズオンをやっていく

## https://karaage.hatenadiary.jp/entry/2018/01/31/073000

## numpy

In [0]:
import numpy as np

## 行列・ベクトルの生成・初期化

In [2]:
W = np.array([[1,2,3],[4,5,6]])
x = np.array([7,8,9])

print(W)
print(x)

[[1 2 3]
 [4 5 6]]
[7 8 9]


In [3]:
print(W.shape)
print(x.shape)

(2, 3)
(3,)


In [4]:
x_row = np.array([[7,8,9]])
x_col = np.array([[7],[8],[9]])

print(x_row.shape)
print(x_col.shape)

(1, 3)
(3, 1)


In [5]:
print(np.zeros(10))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print(np.ones(10))
print(np.ones((3,3)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(np.arange(10))
print(np.arange(3,7))
print(np.arange(1,10,0.1))

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [8]:
print(np.linspace(0,10,21))

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


## 行列・ベクトルの操作

In [9]:
W = np.array([[1,2,3],[4,5,6]])
x =np.array([[7,8,9]])

print(W)
print(W.T)
print()
print(x)
print(x.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]

[[7 8 9]]
[[7]
 [8]
 [9]]


In [10]:
print(W.flatten())

[1 2 3 4 5 6]


In [11]:
print(W.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [12]:
print(np.arange(10).reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
W = np.array([[1,2,3],[4,5,6]])

print(W[0])
print(W[1])
print()

print(W[:,0])
print(W[:,1])
print(W[:,2])
print()

print(W[::-1])
print()

print(W[:,::-1])
print()

print(W[::-1,::-1])

[1 2 3]
[4 5 6]

[1 4]
[2 5]
[3 6]

[[4 5 6]
 [1 2 3]]

[[3 2 1]
 [6 5 4]]

[[6 5 4]
 [3 2 1]]


In [14]:
z = np.arange(20).reshape(4,5)
x = np.zeros((2, 3))
z[1:3,1:4] = x
print(z)

[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15 16 17 18 19]]


In [15]:
x = np.arange(1, 9).reshape(2, 4)
print(x)
print()

y = x[[0, 1, 0, 1], [0, 1, 2, 3]]
print(y)

# z is equivalent as y
# [(0,0), (1,1), (0,2), (1,3)] is zip([0,1,0,1], [0,1,2,3]) 
z = np.array([x[0, 0], x[1, 1], x[0, 2], x[1, 3]])
print(z)
print()

A = np.arange(0,12).reshape(4,3)
print(A)
print()

b = np.array([0, 2, 0, 1])
print(A[np.arange(4), b])      # 各行からbのインデックスに従って抽出
print()

A[np.arange(4), b] += 10
print(A)

[[1 2 3 4]
 [5 6 7 8]]

[1 6 3 8]
[1 6 3 8]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[ 0  5  6 10]

[[10  1  2]
 [ 3  4 15]
 [16  7  8]
 [ 9 20 11]]


In [16]:
a = np.arange(10)
print(a)
print(a < 5)
print(np.where(a < 5))
print()

b = np.arange(50, 60)
print(b)
print(b[a < 5])
print(b[np.where(a < 5)])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
(array([0, 1, 2, 3, 4]),)

[50 51 52 53 54 55 56 57 58 59]
[50 51 52 53 54]
[50 51 52 53 54]


In [17]:
W = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([7, 8, 9])

print(W * 2)
print(-x)

[[ 2  4  6]
 [ 8 10 12]]
[-7 -8 -9]


In [18]:
# 行列での例
W = np.array([[1, 2, 3], [4, 5, 6]])

print(W)
print()

print(W.sum())
print()

print(W.sum(axis=0))
print()

print(W.sum(axis=1))

[[1 2 3]
 [4 5 6]]

21

[5 7 9]

[ 6 15]


In [19]:
# 3階テンソルでの例
A = np.arange(24).reshape(2,3,4)
print(A)
print()

print(A.sum())
print()

print(A.sum(axis=0))
print()

print(A.sum(axis=1))
print()

print(A.sum(axis=2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

276

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[12 15 18 21]
 [48 51 54 57]]

[[ 6 22 38]
 [54 70 86]]


In [20]:
# squared norm
# sqrt(7*7 + 8*8 + 9*9) = 13.928....
x = np.array([7, 8, 9])
np.linalg.norm(x, ord=2)

13.92838827718412